'use strict';
const ICONS = {
 grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
 route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M7 5h9a4 4 0 010 8H8a3 3 0 000 6h9"/>',
 timer:'<circle cx="12" cy="14" r="8"/><path d="M12 10v5l3 2M9 2h6M12 2v4M18 6l2-2"/>',
 repeat:'<path d="M4 9a8 8 0 0114-4l2 3M20 3v5h-5M20 15a8 8 0 01-14 4l-2-3M4 21v-5h5"/>',
 bookmark:'<path d="M6 3h12v18l-6-4-6 4z"/>',
 book:'<path d="M12 5C9 3 5 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1v15"/>',
 chart:'<path d="M4 3v18h17M8 16v-5M13 16V7M18 16V4"/>',
 flame:'<path d="M12 2c2 6-5 7-3 11 2 0 4-2 4-5 4 2 6 5 6 8a7 7 0 01-14 0c0-5 5-6 7-14z"/>',
 wheel:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/><path d="M3 11h6m6 0h6M12 15v6"/>',
 arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 flag:'<path d="M5 22V3m0 0c5-4 9 4 15 0v11c-6 4-10-4-15 0"/>',
 sign:'<path d="m12 3 10 18H2zM12 9v5m0 3v.1"/>',
 road:'<path d="M7 3 3 21M17 3l4 18M12 3v4m0 3v4m0 3v4"/>',
 shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6zM8 12l3 3 5-6"/>',
 distance:'<path d="M3 8v8m18-8v8M3 12h18M7 8l-4 4 4 4m10-8 4 4-4 4"/>',
 star:'<path d="m12 2 3 7 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z"/>',
 target:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/>',
 bolt:'<path d="m13 2-9 12h7l-1 8 10-13h-7z"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>'
};
const icon=(name,cls='')=>`<svg class="icon ${cls}" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name]||ICONS.book}</svg>`;
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
const TOPICS=[
 {id:'signs',name:'Road signs',description:'Know the signs. Read the road.',icon:'sign',color:'orange',pages:'5–10'},
 {id:'rules',name:'Rules of the road',description:'Build your everyday road sense.',icon:'shield',color:'blue',pages:'13–16'},
 {id:'basics',name:'Getting started',description:'Controls, checks & dashboard lights.',icon:'wheel',color:'green',pages:'1–4, 13'},
 {id:'markings',name:'Road markings',description:'Understand every line and crossing.',icon:'road',color:'purple',pages:'11–12'},
 {id:'manoeuvres',name:'Manoeuvres & parking',description:'Make your next move a safe one.',icon:'route',color:'rose',pages:'14, 17–19'},
 {id:'distances',name:'Distances & awareness',description:'Give yourself room to react.',icon:'distance',color:'gold',pages:'15–16, 20'}
];
const KEY='drive-ready-v1';
const blank=DriveStudy.blank;
let state=blank(),storageWorks=true;
try { state=DriveStudy.normalize(JSON.parse(localStorage.getItem(KEY)),QUESTIONS); }
catch(error) { if(error.name!=='SyntaxError')storageWorks=false; }
let timer=null,readerPage=1,toastTimer;
const main=document.querySelector('#main');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function streak(){const dates=new Set(state.days);const d=new Date();if(!dates.has(dateKey(d)))d.setDate(d.getDate()-1);let count=0;while(dates.has(dateKey(d))){count++;d.setDate(d.getDate()-1);}return count;}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageWorks=false;toast('Browser storage is unavailable. Keep this tab open to retain progress.');}updateHeader();}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('visible'),4000);}
function updateHeader(){document.querySelector('#streak-count').textContent=streak();document.querySelector('#mistake-badge').textContent=missed().length;document.querySelector('.local-label').innerHTML=`<span class="tiny-dot"></span>${storageWorks?'Progress saved on this device':'Progress available in this tab'}`;}
const missed=()=>QUESTIONS.filter(q=>state.attempts[q.id]?.last===false||state.needsReview.includes(q.id));
const mastered=(pool=QUESTIONS)=>pool.filter(q=>state.attempts[q.id]?.last===true).length;
function stats(){const values=Object.values(state.attempts);const answered=values.reduce((sum,v)=>sum+v.total,0),correct=values.reduce((sum,v)=>sum+v.correct,0);return{answered,correct,accuracy:answered?Math.round(correct/answered*100):0,seen:values.length};}
const topicBy=id=>TOPICS.find(t=>t.id===id);
const poolBy=id=>QUESTIONS.filter(q=>q.topic===id);
const button=(label,action,extra='',cls='primary')=>`<button class="button ${cls}" data-action="${action}" ${extra}>${label}</button>`;
function heading(kicker,title,description,action=''){return `<div class="page-heading"><div><div class="eyebrow">${kicker}</div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function topicCards(){return TOPICS.map(t=>{const pool=poolBy(t.id),done=mastered(pool);return `<button class="topic-card" data-action="topic" data-topic="${t.id}"><div class="topic-card-top"><span class="topic-icon ${t.color}">${icon(t.icon)}</span><span class="topic-count">${pool.length} questions</span>${icon('arrow','topic-arrow')}</div><h3>${t.name}</h3><p>${t.description}</p><div class="topic-progress"><span>${done?'Keep it going':'Ready when you are'}</span><b>${done} / ${pool.length}</b></div><div class="progress-track"><span style="width:${done/pool.length*100}%"></span></div></button>`;}).join('');}
function home(){const s=stats(),dailyDone=state.daily.includes(dateKey());return `${heading('LET’S MAKE SOME PROGRESS',s.answered?'Welcome back, future driver.':'Your road to passing starts here.','A little practice today. A more confident driver tomorrow.')}<section class="hero"><div class="hero-copy"><span class="hero-tag"><span class="tiny-dot"></span>ONE QUESTION CLOSER</span><h2>Small steps.<br>Big green lights.</h2><p>Turn your driving theory into second nature.<br>Start with a quick, 10-question practice.</p>${button(`Let’s practice ${icon('arrow')}`,'quick')}<span class="hero-foot">${icon('timer')} About 5 minutes <span>·</span> At your own pace</span></div><img class="hero-art" src="assets/road.svg" alt="An illustrated car following a winding road towards its destination"></section>${state.session?`<div class="resume-banner">${icon('route')}<span>You have a round in progress. <strong>${state.session.answers.length} of ${state.session.items.length} answered.</strong></span>${button('Continue →','resume','','secondary small')}</div>`:''}<section class="stat-grid" aria-label="Learning statistics"><div class="stat-card"><span class="stat-icon green">${icon('book')}</span><div><span>Questions explored</span><strong>${s.seen}<small> / ${QUESTIONS.length}</small></strong></div></div><div class="stat-card"><span class="stat-icon blue">${icon('target')}</span><div><span>Answer accuracy</span><strong>${s.answered?s.accuracy+'%':'—'}<small>${s.answered?' across all attempts':'Let’s find your starting point'}</small></strong></div></div><div class="stat-card"><span class="stat-icon orange">${icon('bolt')}</span><div><span>Learning points</span><strong>${state.xp}<small> XP earned</small></strong></div></div></section>${readinessSummary()}<div class="dashboard-grid"><section><div class="section-heading"><div><h2>Choose your route</h2><p>Focus on one topic, one small win at a time.</p></div><a href="#topics" class="text-link">All topics ${icon('arrow')}</a></div><div class="topics-grid">${topicCards()}</div></section><aside class="right-rail"><section class="daily-card"><span class="eyebrow">A LITTLE EVERY DAY</span><span class="daily-star">${icon('star')}</span><h2>Your daily<br>pit stop.</h2><p>5 questions. A fresh mix.<br>Keep the learning habit rolling.</p><div class="daily-details"><span>${icon('timer')} 2–3 min</span><span>${icon('bolt')} +20 bonus XP</span></div>${button(dailyDone?'Completed today ✓':'Take today’s challenge →','daily','',dailyDone?'secondary':'dark')}<span class="subtle centered">${dailyDone?'Come back tomorrow for a fresh mix.':'A new set each day.'}</span></section><section class="book-card"><span class="book-mini">${icon('book')}</span><span class="eyebrow">YOUR SOURCE OF TRUTH</span><h3>Straight from your book.</h3><p>Every question links back to your driving-school study material.</p><a href="#book" class="text-link">Open study book ${icon('arrow')}</a></section></aside></div>`;}
function topicsPage(){return `${heading('PRACTICE BY TOPIC','Take it one turn at a time.','Choose an area to practise. Each round has up to 10 questions, with instant explanations.')}<div class="topics-grid wide">${topicCards()}</div><div class="note">${icon('book')}Questions follow the supplied English driving-school book. Page references use the printed page number.</div>`;}
function challengePage(){return `${heading('TIMED CHALLENGE','Find your rhythm under pressure.','A mixed practice round to see how your knowledge comes together.')}<section class="setup-card"><div class="setup-icon">${icon('timer')}</div><h2>Ready for a little challenge?</h2><p>20 questions from across the book. Your explanations and score appear after you finish.</p><div class="setup-facts"><span><strong>20</strong>questions</span><span><strong>20 min</strong>time limit</span><span><strong>All topics</strong>mixed together</span></div>${button('Start timed challenge '+icon('arrow'),'timed')}<p class="subtle">This is a custom practice format. The book does not specify an official exam duration or pass mark.</p></section>`;}
function questionList(kind){const list=kind==='mistakes'?missed():QUESTIONS.filter(q=>state.saved.includes(q.id)),mistakes=kind==='mistakes';return `${heading(mistakes?'LEARN FROM EVERY TRY':'KEEP THE GOOD STUFF CLOSE',mistakes?'Every mistake is a next step.':'Your saved questions.',mistakes?'Questions you last answered incorrectly. Answer them correctly to clear them from this list.':'Bookmark a question during practice to return to it here.',list.length?button(mistakes?'Practise mistakes →':'Practise saved →',mistakes?'review':'saved-round'):'')} ${list.length?`<div class="question-list">${list.map(q=>`<article class="saved-card">${q.image?`<img src="${q.image}" alt="Study question illustration">`:`<span class="topic-icon ${topicBy(q.topic).color}">${icon(topicBy(q.topic).icon)}</span>`}<div><span class="eyebrow">${topicBy(q.topic).name} · Book p. ${q.page}</span><h3>${esc(q.prompt)}</h3></div>${button('Practise','single',`data-id="${q.id}"`,'secondary small')}${!mistakes?`<button class="icon-button" data-action="remove-saved" data-id="${q.id}" aria-label="Remove saved question">${icon('close')}</button>`:''}</article>`).join('')}</div>`:`<section class="empty-state">${icon(mistakes?'check':'bookmark')}<h2>${mistakes?'A fresh start.':'Make this space your own.'}</h2><p>${mistakes?'Missed questions will appear here after you practise.':'Use the bookmark button on any practice question to save it.'}</p>${button('Start a quick practice →','quick')}</section>`}`;}
const PAGE_TITLES=['Cover','Getting started','Stopping','Dashboard symbols','Lights & steering','Restriction signs','Restriction & direction signs','Mandatory & warning signs','Warning signs','Information signs','Parking & highway signs','Road markings & crossings','Hatched road markings','Theory questions 1–15','Theory questions 16–23','Theory questions 24–35','Theory questions 36–46','Three-point turns','Roundabouts & automatic gears','Turning at junctions','Stopping distances'];
function bookPage(){return `${heading('YOUR ORIGINAL STUDY MATERIAL','The book behind every question.','Browse all 21 scanned pages from your Tuğşan Yazıcı driving-school book.')}<div class="book-intro">${icon('book')}<div><strong>Ders kitabı (İngilizce)</strong><p>English edition · 20 study pages + cover · Available locally</p></div></div><div class="book-grid">${PAGE_TITLES.map((title,i)=>`<button class="book-page" data-action="source" data-page="${i}"><div class="book-preview"><img loading="lazy" src="assets/book/page-${String(i+1).padStart(2,'0')}.jpg" alt="${esc(title)} preview"></div><span class="eyebrow">${i?'BOOK PAGE '+i:'COVER'}</span><h3>${title}</h3></button>`).join('')}</div>`;}
function progressPage(){const s=stats();return `${heading('LOOK HOW FAR YOU’VE COME','Your progress, at a glance.','A record of your practice on this browser. Keep showing up and it adds up.')}<section class="progress-summary"><div class="progress-ring" style="--progress:${mastered()/QUESTIONS.length*100}%"><span><strong>${mastered()}</strong>of ${QUESTIONS.length}</span></div><div><span class="eyebrow">QUESTIONS LAST ANSWERED CORRECTLY</span><h2>${mastered()?'You’re building your road sense.':'Your first milestone is waiting.'}</h2><p>${s.answered} answers · ${s.accuracy}% accuracy · ${state.xp} XP · Level ${Math.floor(state.xp/200)+1}</p><p class="subtle">See your exam-readiness estimate for topic coverage, retention and timed practice.</p></div></section>${readinessSummary()}<div class="topics-grid wide">${topicCards()}</div><section class="history"><h2>Recent rounds</h2>${state.history.length?state.history.slice(0,10).map(h=>`<div class="history-row"><span class="topic-icon green">${icon('flag')}</span><div><strong>${esc(h.label)}</strong><span>${new Date(h.date).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${h.total} questions</span></div><b>${h.correct} / ${h.total}</b><span class="score-tag">${Math.round(h.correct/h.total*100)}%</span></div>`).join(''):'<p class="subtle">Complete a round to see your history here.</p>'}</section>`;}
function shuffle(array,random=Math.random){const a=[...array];for(let i=a.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function dailyRandom(){let seed=Number(dateKey().replaceAll('-',''));return()=>{seed=(Math.imul(1664525,seed)+1013904223)>>>0;return seed/4294967296;};}
function startRound(mode,topic,id){
 if(state.session){renderPending(mode,topic,id);return;}
 beginRound(mode,topic,id);
}
function beginRound(mode,topic,id){let pool=QUESTIONS,limit=10,label='Quick practice';if(mode==='topic'){pool=poolBy(topic);label=topicBy(topic).name;}if(mode==='review'){pool=missed();limit=pool.length;label='Mistake review';}if(mode==='saved-round'){pool=QUESTIONS.filter(q=>state.saved.includes(q.id));limit=pool.length;label='Saved questions';}if(mode==='single'){pool=QUESTIONS.filter(q=>q.id===id);limit=1;label='Focused practice';}if(mode==='smart'){if(topic)pool=poolBy(topic);label=topic?'Focused: '+topicBy(topic).name:'Smart practice';}if(mode==='timed'){limit=20;label='Timed challenge';}if(mode==='daily'){limit=5;label='Daily pit stop';}if(!pool.length){toast('No questions in this collection yet.');return;}
 const random=mode==='daily'?dailyRandom():Math.random;
 // Timed rounds sample each topic before filling the remaining places.
 let chosen=mode==='smart'?DriveStudy.smartQuestions(state,QUESTIONS,limit,topic):shuffle(pool,random).slice(0,limit);
 if(mode==='topic')chosen=DriveStudy.smartQuestions(state,QUESTIONS,limit,topic);
 if(mode==='timed'){const first=TOPICS.map(t=>shuffle(poolBy(t.id))[0]);chosen=shuffle([...first,...shuffle(pool.filter(q=>!first.includes(q))).slice(0,limit-first.length)]);}
 state.session={mode,label,items:chosen.map(q=>({id:q.id,order:shuffle([0,1,2,3],random)})),answers:[],index:0,selected:null,deadline:mode==='timed'?Date.now()+20*60*1000:null,date:dateKey(),assisted:false};save();location.hash='quiz';render();
}
function renderPending(mode,topic,id){clearInterval(timer);main.innerHTML=`${heading('ONE ROUND AT A TIME','You have a practice in progress.','Continue where you left off, or start this new round. Answers already recorded stay in your progress.')}<section class="setup-card"><h2>${esc(state.session.label)}</h2><p>${state.session.answers.length} of ${state.session.items.length} questions answered.</p><div class="button-row">${button('Continue current round','resume')}${button('Start new round','replace-round',`data-mode="${mode}" data-topic="${topic||''}" data-id="${id||''}"`,'secondary')}</div></section>`;}
function quiz(){const session=state.session;if(!session)return home();if(session.deadline&&Date.now()>=session.deadline){finishRound(true);return null;}const item=session.items[session.index],q=QUESTIONS.find(q=>q.id===item.id),answer=session.answers.find(a=>a.id===q.id),show=!!answer&&session.mode!=='timed',selected=answer?answer.selected:session.selected,t=topicBy(q.topic);return `<div class="quiz-top"><button class="text-button" data-action="leave">← Save & leave</button><span>${esc(session.label)}</span><span class="quiz-timer" id="quiz-timer">${session.deadline?timeLeft():icon('bolt')+' '+state.xp+' XP'}</span></div><div class="quiz-progress-line"><span>Question <strong>${session.index+1}</strong> of ${session.items.length}</span><span>${Math.round(session.index/session.items.length*100)}% through</span></div><div class="progress-track quiz-track"><span style="width:${session.index/session.items.length*100}%"></span></div><section class="quiz-card"><div class="quiz-category"><span class="topic-label ${t.color}">${icon(t.icon)}${t.name}</span><button class="icon-button bookmark-button ${state.saved.includes(q.id)?'is-saved':''}" data-action="bookmark" data-id="${q.id}" aria-label="${state.saved.includes(q.id)?'Unsave':'Save'} question" aria-pressed="${state.saved.includes(q.id)}">${icon('bookmark')}</button></div><h1>${esc(q.prompt)}</h1>${q.image?`<div class="question-image"><img src="${q.image}" alt="${q.topic==='signs'?'Road sign':'Dashboard symbol'} to identify"></div>`:''}<div class="answers" role="group" aria-label="Answer choices">${item.order.map((n,i)=>`<button class="answer ${selected===n?'selected':''} ${show&&n===q.answer?'correct':''} ${show&&selected===n&&n!==q.answer?'incorrect':''}" data-action="select" data-choice="${n}" aria-pressed="${selected===n}" ${answer?'disabled':''}><span class="answer-letter">${String.fromCharCode(65+i)}</span><span>${esc(q.options[n])}</span>${show&&n===q.answer?icon('check'):show&&selected===n?icon('close'):''}</button>`).join('')}</div>${show?`<div class="answer-feedback ${answer.correct?'success':'try-again'}" role="status"><strong>${icon(answer.correct?'check':'book')}${answer.correct?'That’s right. Nice work!':'A good one to remember.'}</strong><p>${esc(q.explanation)}</p><button class="text-button" data-action="source" data-page="${q.page}">${icon('book')} See book page ${q.page}</button></div>`:''}<div class="quiz-bottom"><span class="subtle">${show?'One question closer.':'Choose one answer.'}</span>${answer?button(session.index===session.items.length-1?'See my results '+icon('arrow'):'Next question '+icon('arrow'),'next'):button(session.mode==='timed'?(session.index===session.items.length-1?'Finish challenge':'Submit & continue'):'Check answer','check',selected===null?'disabled':'')}</div></section><p class="quiz-hint">${session.mode==='timed'?'Answers and explanations are revealed at the end.':'Take your time. Every answer comes with an explanation.'}</p>`;}
function timeLeft(){const seconds=Math.max(0,Math.ceil((state.session.deadline-Date.now())/1000));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function record(q,selected){const correct=selected===q.answer;const old=state.attempts[q.id]||{total:0,correct:0};state.attempts[q.id]={total:old.total+1,correct:old.correct+(correct?1:0),last:correct,lastAt:new Date().toISOString()};state.needsReview=state.needsReview.filter(id=>id!==q.id);state.xp+=correct?10:2;if(!state.days.includes(dateKey()))state.days.push(dateKey());return{id:q.id,selected,correct};}
function checkAnswer(){const s=state.session;if(!s||s.selected===null||s.answers.some(a=>a.id===s.items[s.index].id))return;if(s.deadline&&Date.now()>=s.deadline){finishRound(true);return;}const q=QUESTIONS.find(q=>q.id===s.items[s.index].id);s.answers.push(s.mode==='timed'?{id:q.id,selected:s.selected,correct:s.selected===q.answer}:record(q,s.selected));save();if(s.mode==='timed')nextQuestion();else render();}
function nextQuestion(){const s=state.session;if(!s)return;if(s.index===s.items.length-1){finishRound();return;}s.index++;s.selected=null;save();render();}
function finishRound(expired=false){const s=state.session;if(!s)return;clearInterval(timer);if(s.mode==='timed'){s.answers=s.answers.map(a=>record(QUESTIONS.find(q=>q.id===a.id),a.selected));state.needsReview=[...new Set([...state.needsReview,...s.items.filter(item=>!s.answers.some(a=>a.id===item.id)).map(item=>item.id)])];}const total=s.items.length,correct=s.answers.filter(a=>a.correct).length;let bonus=0;if(s.mode==='daily'&&s.answers.length===total&&!state.daily.includes(s.date)){state.daily.push(s.date);state.xp+=20;bonus=20;}const result={label:s.label,mode:s.mode,date:new Date().toISOString(),total,correct,answers:s.answers,items:s.items,expired,bonus,assisted:!!s.assisted};state.history.unshift(result);state.history=state.history.slice(0,30);state.session=null;save();location.hash='results';render();}
function resultsPage(){const result=state.history[0];if(!result)return home();const pct=Math.round(result.correct/result.total*100);return `${heading('ANOTHER STEP FORWARD',pct>=80?'Look at you go.':pct>=50?'You’re getting there.':'Every round is a chance to learn.',`${esc(result.label)} complete${result.expired?' — time is up':''}. Let’s turn these answers into lasting knowledge.`)}<section class="result-card"><div class="progress-ring" style="--progress:${pct}%"><span><strong>${pct}%</strong>correct</span></div><div><h2>${result.correct} out of ${result.total} correct</h2><p>${result.total-result.answers.length?`${result.total-result.answers.length} unanswered questions count towards your round score. `:''}${result.bonus?'Daily challenge complete: +20 bonus XP.':'Keep practising the questions that need another look.'}</p><div class="button-row">${button('Practise again →','quick')}${button('Review my mistakes','go-mistakes','','secondary')}</div></div></section>${result.assisted?'<p class="note">You opened study material during this timed round. This result is saved, but does not count towards readiness.</p>':''}${readinessSummary()}<section class="result-review"><h2>Your round, explained</h2>${result.items.map(item=>{const q=QUESTIONS.find(q=>q.id===item.id),a=result.answers.find(a=>a.id===q.id);return `<details class="review-item"><summary><span class="review-status ${a?.correct?'good':'bad'}">${icon(a?.correct?'check':'close')}</span><span>${esc(q.prompt)}${q.image?`<img class="review-thumb" src="${q.image}" alt="Question illustration">`:''}</span><span class="review-summary">${a?a.correct?'Correct':'Review':'Unanswered'}</span></summary><div class="review-body">${a&&!a.correct?`<p>Your answer: ${esc(q.options[a.selected])}</p>`:''}<strong>Correct answer: ${esc(q.options[q.answer])}</strong><p>${esc(q.explanation)}</p><button class="text-button" data-action="source" data-page="${q.page}">Open book page ${q.page} ${icon('arrow')}</button></div></details>`;}).join('')}</section>`;}
function openSource(page){if(state.session?.mode==='timed'){state.session.assisted=true;save();}readerPage=Math.max(0,Math.min(20,Number(page)));document.querySelector('#source-title').textContent=PAGE_TITLES[readerPage];document.querySelector('#source-image').src=`assets/book/page-${String(readerPage+1).padStart(2,'0')}.jpg`;document.querySelector('#reader-page').value=readerPage;document.querySelector('[data-action="prev-page"]').disabled=readerPage===0;document.querySelector('[data-action="next-page"]').disabled=readerPage===20;document.querySelector('.reader-image-wrap').scrollTo(0,0);const dialog=document.querySelector('#source-dialog');if(!dialog.open)dialog.showModal();}
document.querySelector('#reader-page').innerHTML=PAGE_TITLES.map((title,i)=>`<option value="${i}">${i?'Book '+i+' / PDF '+(i+1):'Cover / PDF 1'}</option>`).join('');
document.querySelector('#reader-page').addEventListener('change',e=>openSource(e.target.value));
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const {action,topic,id}=el.dataset;
 if(['quick','daily','timed','topic','review','saved-round','single','smart'].includes(action))startRound(action,topic,id);
 else if(action==='replace-round'){state.session=null;beginRound(el.dataset.mode,topic,id);}
 else if(action==='resume'){location.hash='quiz';render();}
 else if(action==='leave'){location.hash='home';}
 else if(action==='select'){state.session.selected=Number(el.dataset.choice);save();const scroll=window.scrollY;render(false);window.scrollTo(0,scroll);document.querySelector(`[data-action="select"][data-choice="${el.dataset.choice}"]`)?.focus({preventScroll:true});}
 else if(action==='check')checkAnswer();
 else if(action==='next')nextQuestion();
 else if(action==='bookmark'||action==='remove-saved'){state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];save();const scroll=window.scrollY;render(false);window.scrollTo(0,scroll);if(action==='bookmark')document.querySelector('.bookmark-button')?.focus({preventScroll:true});}
 else if(action==='source')openSource(el.dataset.page);
 else if(action==='close-source')document.querySelector('#source-dialog').close();
 else if(action==='prev-page')openSource(readerPage-1);
 else if(action==='next-page')openSource(readerPage+1);
 else if(action==='go-mistakes')location.hash='mistakes';
 else if(action==='menu')document.querySelector('#navigation-dialog').showModal();
 else if(action==='close-menu')document.querySelector('#navigation-dialog').close();
 else if(action==='clear-date'){state.examDate='';save();render(false);toast('Exam date cleared.');}
 else if(action==='export')exportProgress();
 else if(action==='cancel-restore'){pendingImport=null;document.querySelector('#restore-dialog').close();}
 else if(action==='confirm-restore'&&pendingImport){state=pendingImport;pendingImport=null;save();document.querySelector('#restore-dialog').close();render();toast('Progress restored.');}
 else if(action==='zoom-page'){const wrap=document.querySelector('.reader-image-wrap');const zoom=wrap.classList.toggle('zoomed');el.setAttribute('aria-pressed',zoom);el.textContent=zoom?'Fit page':'Zoom in';}

});
function render(focus=true){clearInterval(timer);const route=location.hash.slice(1)||'home';if(state.session?.mode==='timed'&&['book','results'].includes(route)){state.session.assisted=true;save();}document.body.classList.toggle('in-quiz',route==='quiz');const labels={readiness:'Exam readiness',about:'About & privacy',home:'Overview',topics:'Practice by topic',challenge:'Timed challenge',mistakes:'My mistakes',saved:'Saved questions',book:'My study book',progress:'My progress',quiz:'Practice round',results:'Round results'};document.querySelector('#page-label').textContent=labels[route]||'Overview';document.title=(labels[route]||'Overview')+' — DriveReady';document.querySelectorAll('[data-nav],[data-mobile-nav]').forEach(el=>{const active=(el.dataset.nav||el.dataset.mobileNav)===route;el.classList.toggle('active',active);if(active)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});let html;
 if(route==='readiness')html=readinessPage();else if(route==='about')html=aboutPage();else if(route==='topics')html=topicsPage();else if(route==='challenge')html=challengePage();else if(route==='mistakes'||route==='saved')html=questionList(route);else if(route==='book')html=bookPage();else if(route==='progress')html=progressPage();else if(route==='quiz')html=quiz();else if(route==='results')html=resultsPage();else html=home();
 if(html===null)return;main.innerHTML=html;updateHeader();if(focus){window.scrollTo(0,0);main.focus({preventScroll:true});}if(route==='quiz'&&state.session?.deadline)timer=setInterval(()=>{if(Date.now()>=state.session.deadline){finishRound(true);return;}const el=document.querySelector('#quiz-timer');if(el){el.textContent=timeLeft();el.classList.toggle('time-low',state.session.deadline-Date.now()<60000);}},1000);
}
document.querySelector('.skip-link').addEventListener('click',event=>{event.preventDefault();main.focus();main.scrollIntoView();});
window.addEventListener('hashchange',()=>{document.querySelector('#navigation-dialog').close();render();});
document.querySelector('#navigation-dialog').addEventListener('click',event=>{if(event.target.closest('a'))document.querySelector('#navigation-dialog').close();});

document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.session?.deadline&&Date.now()>=state.session.deadline)finishRound(true);});
render();
